apiVersion: apps/v1
kind: Deployment
metadata:
  name: week1-2-app
  labels:
    app: week1-2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week1-2-app
  template:
    metadata:
      labels:
        app: week1-2-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: html
          configMap:
            name: week1-2-app-content
